sudo: false
os:
  - linux
node_js:
  - "6"
  - "8"
  - "10"
language: node_js
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - wget "https://s3.amazonaws.com/bitly-downloads/nsq/nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz"
  - tar zvxf "nsq-1.0.0-compat.linux-amd64.go1.8.tar.gz"
  - export PATH="$PATH:./nsq-1.0.0-compat.linux-amd64.go1.8/bin"
before_script: greenkeeper-lockfile-update
script: npm install-test
after_script: greenkeeper-lockfile-upload
